### ISSUE TITLE
errores front end, no cierra y/o no graba

### ISSUE THREAD

**Issue by fersystem** [avilaton/gtfseditor#152]
creando y editando Trips nos pasó que la ventana de creación de Trips no cerraba luego de clickear "Save Changes". Si se cerraba clickeando "Close"

Luego, de manera aleatoria, algunas veces el Trip estába cargado, y en otras no.

Algo similar pasaba al cargar / editar un Shape para el Trip
![gtfs00](https://cloud.githubusercontent.com/assets/7863644/9116002/663cd630-3c38-11e5-9956-ef69de2012f6.png)
![gtfs1](https://cloud.githubusercontent.com/assets/7863644/9116005/6654a1fc-3c38-11e5-8e73-69806361c6fe.png)
![gtfs01](https://cloud.githubusercontent.com/assets/7863644/9116003/6651e71e-3c38-11e5-9030-5520893d01e8.png)
![gtfs2](https://cloud.githubusercontent.com/assets/7863644/9116004/66530720-3c38-11e5-9b85-9b0682ea6899.png)
![gtfs3](https://cloud.githubusercontent.com/assets/7863644/9116006/665c1234-3c38-11e5-87ed-dbe3ae2bc6fa.png)

**Comment by avilaton** [comment]
@fersystem parte de esto está arreglado en la demo, hoy lo paso a produccion de mendoza.
