### ISSUE TITLE
Necesito reordenar la secuencia de paradas de un trip

### ISSUE THREAD

**Issue by MartinArrastoa** [avilaton/gtfseditor#179]
La secuencia de paradas (en "sequence times") no tiene selector para ordenar las paradas a conveniencia, para lograrlo hay que borrar todas y rehacerlo desde el principio.

**Comment by avilaton** [comment]
Es válido, quizás lo agreguemos en el futuro, pero no borres las paradas para reordenarlas. 

Luego de cargarlas a todas, aún cuando no estén ordenadas, tenemos una herramienta que las ordena automáticamente si el shape está bien cargado. Está en el panel de la izquierda y dice "Sort".

**Comment by avilaton** [comment]
Listo.
