### ISSUE TITLE
Possible incorrect clone url in README

### ISSUE THREAD

**Issue by merlos** [avilaton/gtfseditor#57]
The clone command that appears in README didn't work for me:
```
$ git clone git@github.com:avilaton/gtfseditor.git
```
but it did this one:
```
$ git clone https://github.com/avilaton/gtfseditor.git
```
Regards

**Comment by avilaton** [comment]
Thanks for letting us know, we have fixed that and will update the README soon with a bunch of changes that have not been noted there.
