### ISSUE TITLE
Flask: Add flask-mail support

### ISSUE THREAD

**Issue by avilaton** [avilaton/gtfseditor#64]
See Flasky for reference. This will be needed to complete the registration flow

**Comment by marianodo** [comment]
Do you want to send an automatically email to complete a new register user? Like almost pages that you complete a form and then you receive an email to complete the regitration?

**Comment by avilaton** [comment]
Not for the moment, but we will use it to notify the completion of a build process later on. Let's just have it implemented and ready to use, no need to integrate with anything else for now.
